source 'https://rubygems.org'
ruby '2.5.0'
gem 'rails', '~> 5.2.1'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 3.11'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
gem 'devise'
gem 'pundit'
gem 'slim'
gem 'pry'
gem "twitter-bootstrap-rails", :git => "https://github.com/seyhunak/twitter-bootstrap-rails.git", :branch => "master"
gem 'simple_form'
gem 'haml'
gem 'awesome_rails_console'
gem 'carrierwave'
gem 'mini_magick', '~> 4.3'
gem 'sendgrid-ruby'
gem 'rack-ssl-enforcer'
gem 'ahoy_matey','2.1'
gem 'whois', '~> 4.0'
gem 'will_paginate'
gem 'cloudinary'
gem 'activestorage-cloudinary-service'
gem 'remotipart', github: 'mshibuya/remotipart'
gem 'rails_admin', :git => 'git://github.com/sferik/rails_admin.git'
gem 'rails_admin_rollincode', '~> 1.0'
gem 'rails_admin-i18n'
#gem 'paperclip'
#gem 'aws-sdk-s3'
#gem 'pg_backup'
#gem 'punching_bag'
#gem 'mercadopago'
#gem 'area_do_usuario', path: 'vendor/area_do_usuario'
##################loja virtual#############################
#gem 'spree', '~> 3.2.8'
#gem 'spree_auth_devise', '~> 3.3'
#gem 'spree_gateway', '~> 3.3'
#gem 'spree_i18n', github: 'spree-contrib/spree_i18n'
#gem 'sprockets-helpers', '~> 1.2.1'
#gem 'spree_multi_currency', github: 'spree-contrib/spree_multi_currency'
#gem 'vinsol_spree_themes', github: 'vinsol-spree-contrib/spree_themes', branch: '3-2-stable'

#gem 'solidus'
#gem 'solidus_auth_devise'
#gem 'deface'
#gem 'solidus_i18n', '~> 2.0'
#gem 'rails-i18n', '~> 5.1'
#gem 'kaminari-i18n', '~> 0.5.0'
#gem 'vinsol_spree_themes', github: 'vinsol-spree-contrib/spree_themes', branch: 'master'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'better_errors'
  gem 'pry-rails'
  gem 'binding_of_caller'
  gem 'awesome_print', require:'ap'
end
group :development do
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'rails_real_favicon'
end
