development:
  cloud_name: campinapolis-com
  api_key: '756371992819334'
  api_secret: R4bdImvuKAosNIA4G9XHXWOFiiA
  enhance_image_tag: true
  static_image_support: true
production:
  cloud_name: campinapolis-com
  api_key: '756371992819334'
  api_secret: R4bdImvuKAosNIA4G9XHXWOFiiA
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: campinapolis-com
  api_key: '756371992819334'
  api_secret: R4bdImvuKAosNIA4G9XHXWOFiiA
  enhance_image_tag: true
  static_image_support: true
