development:
  adapter: postgresql
  host: ec2-54-204-8-138.compute-1.amazonaws.com
  database: d8haskh4u8kahd
  url: postgres://apyfoalbdwzgry:eYrnRG5pv-vHw7olqoFYN2elzY@ec2-54-204-8-138.compute-1.amazonaws.com:5432/d8haskh4u8kahd
  username: apyfoalbdwzgry
  password: eYrnRG5pv-vHw7olqoFYN2elzY
  #adapter: postgresql
  #database: campinapolis
  #pool: 5
  #timeout: 5000
  # host: 35.199.95.231
  # adapter: postgresql
  # database: campinapolis
  # username: postgres
  # password: omega200
  # pool: 5
  # timeout: 5000

test:
  adapter: postgresql
  database: campinapolis
  pool: 5
  timeout: 5000

production:
  #url: <%= ENV["GOOGLE_SQL"] %>
  host: 35.199.95.231
  adapter: postgresql
  database: campinapolis
  username: postgres
  password: omega200
  pool: 5
  timeout: 5000